dist: trusty
language: cpp
compiler: gcc
addons: 
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      
install:
  - curl -sL https://github.com/opencv/opencv/archive/3.4.1.zip > opencv.zip
  - unzip opencv.zip
  - cd opencv-3.4.1
  - mkdir release
  - cd release
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ..
  - make -j4 
  - sudo make install
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
  - sudo ldconfig
  - cd ../..

script:
  - cd [project_dir]
  - cmake .
  - make all

notifications:
  email: false


