sudo: required

language: c++

services:
  - docker

before_install:
  - docker pull warc3l/owlies
  
script:
  - docker run -v /Owlies:/Owlies -it warc3l/owlies
  - cmake ..
  - make 
  - docker ps -a

notifications:
  email: false


