sudo: required

language: c++

services:
  - docker

before_install:
  - docker pull warc3l/owlies:latest
  - docker run -itd --name owlies warc3l/owlies
  - docker exec owlies git clone https://www.github.com/warc3l/owlies.git /Owlies

script:
  - docker exec owlies cmake /Owlies
  - docker exec owlies make /Owlies

notifications:
  email: false


