dist: trusty
language: cpp
compiler: gcc
addons: 
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      
install:
  # Qt libraries
  # OpenCV libraries
  - curl -sL https://github.com/opencv/opencv/archive/3.4.1.zip > opencv.zip
  - unzip opencv.zip
  - cd opencv-3.4.1
  - mkdir release
  - cd release
  - cmake -D CMAKE_BUILD_TYPE=RELEASE -D CMAKE_INSTALL_PREFIX=/usr/local ..
  - make -j4 
  - sudo make install
  - sudo sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'
  - sudo ldconfig
  - cd ../..
  # Boost libraries
  - wget https://downloads.sourceforge.net/project/boost/boost/1.61.0/boost_1_61_0.tar.bz2?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fboost%2Ffiles%2Fboost%2F1.61.0%2Fboost_1_61_0.tar.bz2%2Fdownload&ts=1524602759
  - tar --bzip2 -xf boost_1_61_0.tar.bz
  - cd boost_1_61_0
  - mkdir boost-build
  - ./bootstrap.sh --prefix=./boost-build
  - ./b2 install

script:
  - cd [project_dir]
  - cmake .
  - make all

notifications:
  email: false


