# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/marcel/Downloads/cmake-3.10.3-Linux-x86_64/bin/cmake

# The command to remove a file.
RM = /home/marcel/Downloads/cmake-3.10.3-Linux-x86_64/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/marcel/GitProjects/Owlies

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/marcel/GitProjects/Owlies

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/marcel/Downloads/cmake-3.10.3-Linux-x86_64/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/home/marcel/Downloads/cmake-3.10.3-Linux-x86_64/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcel/GitProjects/Owlies/CMakeFiles /home/marcel/GitProjects/Owlies/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/marcel/GitProjects/Owlies/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Owlies

# Build rule for target.
Owlies: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Owlies
.PHONY : Owlies

# fast build rule for target.
Owlies/fast:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/build
.PHONY : Owlies/fast

#=============================================================================
# Target rules for targets named Owlies_autogen

# Build rule for target.
Owlies_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Owlies_autogen
.PHONY : Owlies_autogen

# fast build rule for target.
Owlies_autogen/fast:
	$(MAKE) -f CMakeFiles/Owlies_autogen.dir/build.make CMakeFiles/Owlies_autogen.dir/build
.PHONY : Owlies_autogen/fast

Owlies_autogen/mocs_compilation.o: Owlies_autogen/mocs_compilation.cpp.o

.PHONY : Owlies_autogen/mocs_compilation.o

# target to build an object file
Owlies_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/Owlies_autogen/mocs_compilation.cpp.o
.PHONY : Owlies_autogen/mocs_compilation.cpp.o

Owlies_autogen/mocs_compilation.i: Owlies_autogen/mocs_compilation.cpp.i

.PHONY : Owlies_autogen/mocs_compilation.i

# target to preprocess a source file
Owlies_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/Owlies_autogen/mocs_compilation.cpp.i
.PHONY : Owlies_autogen/mocs_compilation.cpp.i

Owlies_autogen/mocs_compilation.s: Owlies_autogen/mocs_compilation.cpp.s

.PHONY : Owlies_autogen/mocs_compilation.s

# target to generate assembly for a file
Owlies_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/Owlies_autogen/mocs_compilation.cpp.s
.PHONY : Owlies_autogen/mocs_compilation.cpp.s

controllers/main_window.o: controllers/main_window.cc.o

.PHONY : controllers/main_window.o

# target to build an object file
controllers/main_window.cc.o:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/controllers/main_window.cc.o
.PHONY : controllers/main_window.cc.o

controllers/main_window.i: controllers/main_window.cc.i

.PHONY : controllers/main_window.i

# target to preprocess a source file
controllers/main_window.cc.i:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/controllers/main_window.cc.i
.PHONY : controllers/main_window.cc.i

controllers/main_window.s: controllers/main_window.cc.s

.PHONY : controllers/main_window.s

# target to generate assembly for a file
controllers/main_window.cc.s:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/controllers/main_window.cc.s
.PHONY : controllers/main_window.cc.s

controllers/toolbox.o: controllers/toolbox.cc.o

.PHONY : controllers/toolbox.o

# target to build an object file
controllers/toolbox.cc.o:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/controllers/toolbox.cc.o
.PHONY : controllers/toolbox.cc.o

controllers/toolbox.i: controllers/toolbox.cc.i

.PHONY : controllers/toolbox.i

# target to preprocess a source file
controllers/toolbox.cc.i:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/controllers/toolbox.cc.i
.PHONY : controllers/toolbox.cc.i

controllers/toolbox.s: controllers/toolbox.cc.s

.PHONY : controllers/toolbox.s

# target to generate assembly for a file
controllers/toolbox.cc.s:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/controllers/toolbox.cc.s
.PHONY : controllers/toolbox.cc.s

gui/subclasses/image_label.o: gui/subclasses/image_label.cc.o

.PHONY : gui/subclasses/image_label.o

# target to build an object file
gui/subclasses/image_label.cc.o:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/gui/subclasses/image_label.cc.o
.PHONY : gui/subclasses/image_label.cc.o

gui/subclasses/image_label.i: gui/subclasses/image_label.cc.i

.PHONY : gui/subclasses/image_label.i

# target to preprocess a source file
gui/subclasses/image_label.cc.i:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/gui/subclasses/image_label.cc.i
.PHONY : gui/subclasses/image_label.cc.i

gui/subclasses/image_label.s: gui/subclasses/image_label.cc.s

.PHONY : gui/subclasses/image_label.s

# target to generate assembly for a file
gui/subclasses/image_label.cc.s:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/gui/subclasses/image_label.cc.s
.PHONY : gui/subclasses/image_label.cc.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/main.cpp.s
.PHONY : main.cpp.s

model/image.o: model/image.cc.o

.PHONY : model/image.o

# target to build an object file
model/image.cc.o:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/model/image.cc.o
.PHONY : model/image.cc.o

model/image.i: model/image.cc.i

.PHONY : model/image.i

# target to preprocess a source file
model/image.cc.i:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/model/image.cc.i
.PHONY : model/image.cc.i

model/image.s: model/image.cc.s

.PHONY : model/image.s

# target to generate assembly for a file
model/image.cc.s:
	$(MAKE) -f CMakeFiles/Owlies.dir/build.make CMakeFiles/Owlies.dir/model/image.cc.s
.PHONY : model/image.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Owlies"
	@echo "... Owlies_autogen"
	@echo "... Owlies_autogen/mocs_compilation.o"
	@echo "... Owlies_autogen/mocs_compilation.i"
	@echo "... Owlies_autogen/mocs_compilation.s"
	@echo "... controllers/main_window.o"
	@echo "... controllers/main_window.i"
	@echo "... controllers/main_window.s"
	@echo "... controllers/toolbox.o"
	@echo "... controllers/toolbox.i"
	@echo "... controllers/toolbox.s"
	@echo "... gui/subclasses/image_label.o"
	@echo "... gui/subclasses/image_label.i"
	@echo "... gui/subclasses/image_label.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... model/image.o"
	@echo "... model/image.i"
	@echo "... model/image.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

